package com.wbg.swager.dao;

import com.wbg.swager.entity.User;
import org.apache.ibatis.annotations.Param;

import javax.ws.rs.PathParam;
import java.util.List;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated
     */
    User selectByPrimaryKey(Integer id);

    List<User> selectByUserName(String username);

    List<User> selectByStatus(String userStatus);
    List<User> selectByFirstName(String firstname);
    List<User> selectUsername(String username);



    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated
     */
    List<User> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(User record);

    int updateByPrimaryKeys(@Param("username") String username,@Param("firstname")String firstname,@Param("lastname")String lastname,@Param("email")String email,@Param("password")String password,@Param("phone")String phone,@Param("userstatus")String userstatus);
    int updateByUserName(String username);

    int deleteByUserName(@Param("username") String username);

    int Login(@Param("username") String username , @Param("password") String password);
}